baseURL = "https://bnextmedia.github.io/AINEXT/"
languageCode = "zh-TW"
title = "AINEXT"
theme = "newsroom"
author = "James"
canonifyurls = true

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 10

[params]
  description = "AI 閱讀筆記與產業觀察"
  # defaultMode = "dark"  # 取消註解可設定預設深色模式

[outputs]
  home = ["HTML", "RSS", "JSON"]
